# Generated by Django 5.2.16 on 2026-08-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_created',
            new_name='is_completed',
        ),
    ]
